apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: web-flask-api
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: my-application/flask-app:0.0.1  # 後ほど作成するDockerイメージの名前
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017/"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: web-flask-api
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30050
    protocol: TCP
  selector:
    app: flask-app
