apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: web-flask-api
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: my-application/frontend:0.0.1
        ports:
        - containerPort: 4173
        env:
        - name: VITE_ML_PREDICT_URI
          value: "http://localhost:30000/predict"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: web-flask-api
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 4173
    targetPort: 4173
    nodePort: 30417
    