FROM python:3.10-buster

# 作業ディレクトリの設定
WORKDIR /app

# 依存関係ファイルをコピーしてインストール
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# アプリケーションのコードとモデルをコピー
COPY app.py .
COPY model.joblib .

# Flaskサーバーのポートを公開
EXPOSE 5000

# アプリケーションの起動
CMD ["python", "app.py"]
